name: moda
channels:
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda=11.7
  - cuda-cccl
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-cudart
  - cuda-cudart-dev
  - cuda-cuobjdump
  - cuda-cupti
  - cuda-cuxxfilt
  - cuda-driver-dev
  - cuda-gdb
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-memcheck
  - cuda-nsight
  - cuda-nsight-compute
  - cuda-nvcc
  - cuda-nvdisasm
  - cuda-nvml-dev
  - cuda-nvprof
  - cuda-nvprune
  - cuda-nvrtc
  - cuda-nvrtc-dev
  - cuda-nvtx
  - cuda-nvvp
  - cuda-runtime
  - cuda-samples
  - cuda-sanitizer-api
  - cuda-toolkit
  - cuda-tools
  - cuda-visual-tools
  - flit-core
  - freetype
  - fvcore
  - gds-tools
  - giflib
  - gmp
  - gnutls
  - idna
  - intel-openmp
  - iopath
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libcublas
  - libcublas-dev
  - libcufft
  - libcufft-dev
  - libcufile
  - libcufile-dev
  - libcurand
  - libcurand-dev
  - libcusolver
  - libcusparse
  - libcusparse-dev
  - libdeflate
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libnpp
  - libnpp-dev
  - libnvjpeg
  - libnvjpeg-dev
  - libpng=1.6.39
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - nsight-compute
  - numpy
  - numpy-base
  - openh264
  - openssl
  - pillow
  - pip
  - portalocker
  - pycparser
  - pyopenssl
  - pysocks
  - python=3.9
  - python_abi=3.9
  - pytorch
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - pyyaml
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tabulate
  - termcolor
  - torchvision=py39_cu116
  - tqdm
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yacs
  - yaml
  - zlib
  - zstd
  - pip:
      - absl-py
      - rich
      - attrs
      - cachetools
      - chumpy
      - contourpy
      - cycler
      - flatbuffers
      - fonttools
      - grpcio
      - imageio
      - importlib-metadata
      - importlib-resources
      - lazy-loader
      - llvmlite
      - markdown
      - markupsafe
      - matplotlib
      - mediapipe
      - networkx
      - numba
      - oauthlib
      - opencv-contrib-python
      - opencv-python
      - packaging
      - protobuf
      - pyasn1
      - pyasn1-modules
      - pyparsing
      - python-dateutil
      - pywavelets
      - requests-oauthlib
      - rsa
      - scikit-image
      - scipy
      - sounddevice
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - tifffile
      - werkzeug
      - zipp
