task: TrainMODAVel
batch_size: 32
n_epochs: 5000
gpu_ids: [0,]
dataset_mode: audio2repr
model: moda
subject_head: point
body: dualv2
loss: L2+Velocity

dataroot: assets/dataset/HDTF
train_sub_names: train.txt
test_sub_names: test.txt
ref_sub_names: train.txt